name: CrayolaPlugin
main: com.gmail.anthonythegu.crayolaplugin.Main
version: 0.10.18
api-version: 1.19
author: Crayola#2819
description: Adds the ability to pray, offer items, and be blessed/cursed!
commands:
  remindme:
    description: Reminds you after a set time
  crayolapluginconfigreload:
    description: Reloads the config